// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCwYjwCsCamU_aQVfv8hQWaGMsVpi3OI',
    appId: '1:698083644545:web:292286e72e862cfb1ea980',
    messagingSenderId: '698083644545',
    projectId: 'padelistas-dev',
    authDomain: 'padelistas-dev.firebaseapp.com',
    storageBucket: 'padelistas-dev.appspot.com',
    measurementId: 'G-8SXY9TW3G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-cdeV4j0J-RDvjKTKexik008YcH_Aad8',
    appId: '1:698083644545:android:d863753cffc7f7f51ea980',
    messagingSenderId: '698083644545',
    projectId: 'padelistas-dev',
    storageBucket: 'padelistas-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnvcIVSPbo1NaGXO3P7hefdw1sN06PrSk',
    appId: '1:698083644545:ios:ae31dfa549091dd01ea980',
    messagingSenderId: '698083644545',
    projectId: 'padelistas-dev',
    storageBucket: 'padelistas-dev.appspot.com',
    iosBundleId: 'com.example.padelistas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnvcIVSPbo1NaGXO3P7hefdw1sN06PrSk',
    appId: '1:698083644545:ios:311e5fa1afe107a91ea980',
    messagingSenderId: '698083644545',
    projectId: 'padelistas-dev',
    storageBucket: 'padelistas-dev.appspot.com',
    iosBundleId: 'com.example.padelistas.RunnerTests',
  );
}
