// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdZxxycrzGuvrGbo5DYBYnhRQs76l4Zh0',
    appId: '1:111567119844:web:4569b3b053c39c229813f1',
    messagingSenderId: '111567119844',
    projectId: 'padelistas-app',
    authDomain: 'padelistas-app.firebaseapp.com',
    storageBucket: 'padelistas-app.appspot.com',
    measurementId: 'G-REYXBQ6Z76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf45pn0b1SpGoyON_0GbNImSUI4bNus5E',
    appId: '1:111567119844:android:d9a5a92e493351469813f1',
    messagingSenderId: '111567119844',
    projectId: 'padelistas-app',
    storageBucket: 'padelistas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiF3l3Rv92Cf2lwK9kA-Hchg3xa03hSfA',
    appId: '1:111567119844:ios:c377542cdb5ad4a09813f1',
    messagingSenderId: '111567119844',
    projectId: 'padelistas-app',
    storageBucket: 'padelistas-app.appspot.com',
    iosBundleId: 'com.example.padelistas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiF3l3Rv92Cf2lwK9kA-Hchg3xa03hSfA',
    appId: '1:111567119844:ios:cbe43f0536fe4bbf9813f1',
    messagingSenderId: '111567119844',
    projectId: 'padelistas-app',
    storageBucket: 'padelistas-app.appspot.com',
    iosBundleId: 'com.example.padelistas.RunnerTests',
  );
}
